# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'Azure_JMeter'
    loadTestConfigFile: 'drudge.jmx'
    resourceGroup: 'iTheasLoadTestPreview'
    loadTestResource: 'iTheasLoadTestPeview'
